I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 14, in script
    $ renpy.random.shuffle(questionlist) # shuffle the questionlist
  File "game/script.rpy", line 14, in <module>
    $ renpy.random.shuffle(questionlist) # shuffle the questionlist
NameError: name 'questionlist' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 14, in script
    $ renpy.random.shuffle(questionlist) # shuffle the questionlist
  File "/Users/DivyaP/Downloads/renpy-6.99.14.3-sdk/renpy/ast.py", line 862, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/DivyaP/Downloads/renpy-6.99.14.3-sdk/renpy/python.py", line 1888, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 14, in <module>
    $ renpy.random.shuffle(questionlist) # shuffle the questionlist
NameError: name 'questionlist' is not defined

Darwin-16.7.0-x86_64-i386-64bit
Ren'Py 6.99.14.3.3347
Res Novae 1.0
Sun Apr 29 01:28:44 2018
